package com.alexnevsky.FacemashAndroid.storage;

import com.alexnevsky.FacemashAndroid.model.Face;

import java.util.Collections;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * User: Alex Nevsky
 * Date: 04.10.13
 */
public class Base {

	private static int[] girlsFaceIdArray;
	private static int[] boysFaceIdArray;
	private static final Map<Long, Face> girlsFaceMap = new ConcurrentHashMap<Long, Face>(384);
	private static final Map<Long, Face> boysFaceMap = new ConcurrentHashMap<Long, Face>(384);

	static {
		Face face;

		//girls
		face = new Face("Abbie", "Cornish", "faces_girls_abbie_cornish");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Adriana", "Lima", "faces_girls_adriana_lima");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Agnes", "Bruckner", "faces_girls_agnes_bruckner");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ahna", "Oreilly", "faces_girls_ahna_oreilly");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Aj", "Cook", "faces_girls_aj_cook");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alessandra", "Ambrosio", "faces_girls_alessandra_ambrosio");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alexandra", "Krosney", "faces_girls_alexandra_krosney");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alexandra", "Siegel", "faces_girls_alexandra_siegel");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alexis", "Knapp", "faces_girls_alexis_knapp");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ali", "Larter", "faces_girls_ali_larter");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alice", "Englert", "faces_girls_alice_englert");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alison", "Brie", "faces_girls_alison_brie");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Allie", "Gonino", "faces_girls_allie_gonino");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Allison", "Williams", "faces_girls_allison_williams");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Alona", "Tal", "faces_girls_alona_tal");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amanda", "Seyfried", "faces_girls_amanda_seyfried");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amber", "Heard", "faces_girls_amber_heard");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amrita", "Acharia", "faces_girls_amrita_acharia");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Amy", "Roiland", "faces_girls_amy_roiland");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ana", "Beatriz Barros", "faces_girls_ana_beatriz_barros");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Andi", "Muise", "faces_girls_andi_muise");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Andrea", "Gabriel", "faces_girls_andrea_gabriel");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Angela", "Besharah", "faces_girls_angela_besharah");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Angela", "Lindvall", "faces_girls_angela_lindvall");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Angelina", "Jolie", "faces_girls_angelina_jolie");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anna", "Camp", "faces_girls_anna_camp");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anna", "Kendrick", "faces_girls_anna_kendrick");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anndi", "Mcafee", "faces_girls_anndi_mcafee");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Anne", "Hathaway", "faces_girls_anne_hathaway");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Annie", "Hall", "faces_girls_annie_hall");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Antoinette", "Kalaj", "faces_girls_antoinette_kalaj");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashleigh", "Dejon", "faces_girls_ashleigh_dejon");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashleigh", "Harrington", "faces_girls_ashleigh_harrington");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Bell", "faces_girls_ashley_bell");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Benson", "faces_girls_ashley_benson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Greene", "faces_girls_ashley_greene");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Laurence", "faces_girls_ashley_laurence");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ashley", "Schnacky", "faces_girls_ashley_schnacky");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ava", "Gaudet", "faces_girls_ava_gaudet");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Bar", "Refaeli", "faces_girls_bar_refaeli");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Beatrice", "King", "faces_girls_beatrice_king");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Beau", "Garrett", "faces_girls_beau_garrett");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Bella", "Heathcote", "faces_girls_bella_heathcote");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Blake", "Lively", "faces_girls_blake_lively");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Brit", "Marling", "faces_girls_brit_marling");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Brooke", "Butler", "faces_girls_brooke_butler");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Brooklyn", "Sudano", "faces_girls_brooklyn_sudano");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Bryce", "Dallas Howard", "faces_girls_bryce_dallas_howard");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Caitlin", "Stasey", "faces_girls_caitlin_stasey");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Camilla", "Belle", "faces_girls_camilla_belle");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Candice", "Accola", "faces_girls_candice_accola");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Candice", "Swanepoel", "faces_girls_candice_swanepoel");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cara", "Delevingne", "faces_girls_cara_delevingne");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carey", "Mulligan", "faces_girls_carey_mulligan");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carla", "Gallo", "faces_girls_carla_gallo");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Caroline", "De Souza correa", "faces_girls_caroline_de_souza_correa");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Caroline", "Dhavernas", "faces_girls_caroline_dhavernas");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carrie", "Anne Moss", "faces_girls_carrie_anne_moss");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Carrie", "Collins", "faces_girls_carrie_collins");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Casey", "Carolan", "faces_girls_casey_carolan");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cat", "Hartmann", "faces_girls_cat_hartmann");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Charlize", "Theron", "faces_girls_charlize_theron");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Chasty", "Ballesteros", "faces_girls_chasty_ballesteros");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Chenoa", "Mason", "faces_girls_chenoa_mason");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Christina", "Cannon", "faces_girls_christina_cannon");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Christina", "Ricci", "faces_girls_christina_ricci");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Christine", "Marzano", "faces_girls_christine_marzano");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cindy", "Sampson", "faces_girls_cindy_sampson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cindy", "Vela", "faces_girls_cindy_vela");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Claire", "Julien", "faces_girls_claire_julien");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Claudia", "Black", "faces_girls_claudia_black");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Cristine", "Prosperi", "faces_girls_cristine_prosperi");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Dakota", "Fanning", "faces_girls_dakota_fanning");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Daniela", "Dib", "faces_girls_daniela_dib");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Daria", "Werbowy", "faces_girls_daria_werbowy");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Debra", "Harrison Lowe", "faces_girls_debra_harrison_lowe");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Demi", "Moore", "faces_girls_demi_moore");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Desi", "Ivanova", "faces_girls_desi_ivanova");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Diane", "Kruger", "faces_girls_diane_kruger");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Doutzen", "Kroes", "faces_girls_doutzen_kroes");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eleanor", "Tomlinson", "faces_girls_eleanor_tomlinson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elena", "Anaya", "faces_girls_elena_anaya");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eleni", "Nico", "faces_girls_eleni_nico");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elisabeth", "Moss", "faces_girls_elisabeth_moss");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elisabetta", "Fantone", "faces_girls_elisabetta_fantone");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elisha", "Cuthbert", "faces_girls_elisha_cuthbert");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elizabeth", "Hurley", "faces_girls_elizabeth_hurley");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elizabeth", "Mathis", "faces_girls_elizabeth_mathis");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Elizabeth", "Mitchell", "faces_girls_elizabeth_mitchell");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ellen", "Page", "faces_girls_ellen_page");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Embeth", "Davidtz", "faces_girls_embeth_davidtz");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emilia", "Clarke", "faces_girls_emilia_clarke");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emilie", "De Ravin", "faces_girls_emilie_de_ravin");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Blunt", "faces_girls_emily_blunt");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Deschanel", "faces_girls_emily_deschanel");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Hampshire", "faces_girls_emily_hampshire");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Kinney", "faces_girls_emily_kinney");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Robison", "faces_girls_emily_robison");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emily", "Vancamp", "faces_girls_emily_vancamp");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emma", "Stone", "faces_girls_emma_stone");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emma", "Watson", "faces_girls_emma_watson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emmanuelle", "Chriqui", "faces_girls_emmanuelle_chriqui");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emmanuelle", "Vaugier", "faces_girls_emmanuelle_vaugier");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Emmy", "Rossum", "faces_girls_emmy_rossum");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Erica", "Cerra", "faces_girls_erica_cerra");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Erin", "Keller", "faces_girls_erin_keller");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eva", "Green", "faces_girls_eva_green");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eva", "Mendes", "faces_girls_eva_mendes");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Evangeline", "Lilly", "faces_girls_evangeline_lilly");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Evanna", "Lynch", "faces_girls_evanna_lynch");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eve", "Hewson", "faces_girls_eve_hewson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Eve", "Mauro", "faces_girls_eve_mauro");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Famke", "Janssen", "faces_girls_famke_janssen");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Flavia", "De Oliveira", "faces_girls_flavia_de_oliveira");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Florence", "Faivre", "faces_girls_florence_faivre");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gal", "Gadot", "faces_girls_gal_gadot");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gemma", "Arterton", "faces_girls_gemma_arterton");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Genesis", "Rodriguez", "faces_girls_genesis_rodriguez");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Georgia", "King", "faces_girls_georgia_king");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gina", "Carano", "faces_girls_gina_carano");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gisele", "Bundchen", "faces_girls_gisele_bundchen");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gugu", "Mbatha Raw", "faces_girls_gugu_mbatha_raw");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gwendoline", "Taylor", "faces_girls_gwendoline_taylor");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Gwyneth", "Paltrow", "faces_girls_gwyneth_paltrow");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Halle", "Berry", "faces_girls_halle_berry");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hana", "Jirickova", "faces_girls_hana_jirickova");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hana", "Soukupova", "faces_girls_hana_soukupova");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hannah", "Marks", "faces_girls_hannah_marks");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hayden", "Panettiere", "faces_girls_hayden_panettiere");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Heather", "Marks", "faces_girls_heather_marks");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Heather", "Morris", "faces_girls_heather_morris");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Heidi", "Klum", "faces_girls_heidi_klum");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Helena", "Christensen", "faces_girls_helena_christensen");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Hilary", "Rhoda", "faces_girls_hilary_rhoda");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ingrid", "Graham", "faces_girls_ingrid_graham");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Isabel", "Lucas", "faces_girls_isabel_lucas");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Izabel", "Goulart", "faces_girls_izabel_goulart");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jacqueline", "Macinnes Wood", "faces_girls_jacqueline_macinnes_wood");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jaime", "King", "faces_girls_jaime_king");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jaimie", "Alexander", "faces_girls_jaimie_alexander");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jeisa", "Chiminazzo", "faces_girls_jeisa_chiminazzo");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jenna", "Dewan Tatum", "faces_girls_jenna_dewan_tatum");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Aniston", "faces_girls_jennifer_aniston");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Connelly", "faces_girls_jennifer_connelly");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Garner", "faces_girls_jennifer_garner");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Kristin Cox", "faces_girls_jennifer_kristin_cox");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jennifer", "Lawrence", "faces_girls_jennifer_lawrence");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Alba", "faces_girls_jessica_alba");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Brown Findlay", "faces_girls_jessica_brown_findlay");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Clark", "faces_girls_jessica_clark");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Lucas", "faces_girls_jessica_lucas");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Pare", "faces_girls_jessica_pare");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jessica", "Parker Kennedy", "faces_girls_jessica_parker_kennedy");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jo", "Beth Locklear", "faces_girls_jo_beth_locklear");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Jocelin", "Donahue", "faces_girls_jocelin_donahue");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Benson", "faces_girls_julia_benson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Roberts", "faces_girls_julia_roberts");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Stegner", "faces_girls_julia_stegner");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Stiles", "faces_girls_julia_stiles");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julia", "Voth", "faces_girls_julia_voth");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Julianne", "Moore", "faces_girls_julianne_moore");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kalilah", "Harris", "faces_girls_kalilah_harris");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Karolina", "Kurkova", "faces_girls_karolina_kurkova");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kat", "Dennings", "faces_girls_kat_dennings");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kate", "Beckinsale", "faces_girls_kate_beckinsale");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kate", "Hudson", "faces_girls_kate_hudson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kate", "Winslet", "faces_girls_kate_winslet");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katherine", "Heigl", "faces_girls_katherine_heigl");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katheryn", "Winnick", "faces_girls_katheryn_winnick");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kathleen", "Robertson", "faces_girls_kathleen_robertson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katie", "Cassidy", "faces_girls_katie_cassidy");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katie", "Powers", "faces_girls_katie_powers");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Katy", "Perry", "faces_girls_katy_perry");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Keira", "Knightley", "faces_girls_keira_knightley");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Keri", "Russell", "faces_girls_keri_russell");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kerry", "Washington", "faces_girls_kerry_washington");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kiele", "Sanchez", "faces_girls_kiele_sanchez");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kirsten", "Dunst", "faces_girls_kirsten_dunst");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kiva", "Dawson", "faces_girls_kiva_dawson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kristen", "Bell", "faces_girls_kristen_bell");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Kristen", "Stewart", "faces_girls_kristen_stewart");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Ksenia", "Solo", "faces_girls_ksenia_solo");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laura", "Harring", "faces_girls_laura_harring");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laura", "Mennell", "faces_girls_laura_mennell");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laura", "Vandervoort", "faces_girls_laura_vandervoort");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Cohan", "faces_girls_lauren_cohan");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Jenkins", "faces_girls_lauren_jenkins");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Lee Smith", "faces_girls_lauren_lee_smith");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lauren", "Storm", "faces_girls_lauren_storm");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laurence", "Leboeuf", "faces_girls_laurence_leboeuf");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Laurie", "Holden", "faces_girls_laurie_holden");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lea", "Michele", "faces_girls_lea_michele");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Leda", "Lum", "faces_girls_leda_lum");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Leighton", "Meester", "faces_girls_leighton_meester");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Leila", "Lopes", "faces_girls_leila_lopes");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lena", "Headey", "faces_girls_lena_headey");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lesley", "Ann Brandt", "faces_girls_lesley_ann_brandt");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lindsay", "Burdge", "faces_girls_lindsay_burdge");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisa", "Brenner", "faces_girls_lisa_brenner");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisa", "Chandler", "faces_girls_lisa_chandler");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisa", "Edelstein", "faces_girls_lisa_edelstein");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lisamarie", "Costabile", "faces_girls_lisamarie_costabile");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Liv", "Tyler", "faces_girls_liv_tyler");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Liya", "Kebede", "faces_girls_liya_kebede");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Louise", "Monot", "faces_girls_louise_monot");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lucy", "Hale", "faces_girls_lucy_hale");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Lymari", "Nadal", "faces_girls_lymari_nadal");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Maggie", "Grace", "faces_girls_maggie_grace");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Maggie", "Gyllenhaal", "faces_girls_maggie_gyllenhaal");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Malaya", "Rivera Drew", "faces_girls_malaya_rivera_drew");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Margo", "Harshman", "faces_girls_margo_harshman");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Margot", "Robbie", "faces_girls_margot_robbie");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Maria", "Grazia Cucinotta", "faces_girls_maria_grazia_cucinotta");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Marion", "Cotillard", "faces_girls_marion_cotillard");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Marnette", "Patterson", "faces_girls_marnette_patterson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mary", "Elizabeth Winstead", "faces_girls_mary_elizabeth_winstead");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Megan", "Fox", "faces_girls_megan_fox");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Melanie", "Minichino", "faces_girls_melanie_minichino");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Melissa", "Joan Hart", "faces_girls_melissa_joan_hart");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mia", "Sara", "faces_girls_mia_sara");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Michaela", "Mcmanus", "faces_girls_michaela_mcmanus");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Michelle", "Borth", "faces_girls_michelle_borth");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mila", "Kunis", "faces_girls_mila_kunis");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Miranda", "Kerr", "faces_girls_miranda_kerr");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Mischa", "Barton", "faces_girls_mischa_barton");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Missy", "Peregrym", "faces_girls_missy_peregrym");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Monica", "Bellucci", "faces_girls_monica_bellucci");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Montserrat", "Oliver", "faces_girls_montserrat_oliver");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Morena", "Baccarin", "faces_girls_morena_baccarin");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Najwa", "Nimri", "faces_girls_najwa_nimri");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nash", "Carter", "faces_girls_nash_carter");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natalia", "Tena", "faces_girls_natalia_tena");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natalie", "Martinez", "faces_girls_natalie_martinez");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natalie", "Portman", "faces_girls_natalie_portman");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Natasha", "Henstridge", "faces_girls_natasha_henstridge");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nazneen", "Contractor", "faces_girls_nazneen_contractor");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nicole", "De Boer", "faces_girls_nicole_de_boer");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nicole", "Kidman", "faces_girls_nicole_kidman");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nihan", "Gur", "faces_girls_nihan_gur");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nikki", "Reed", "faces_girls_nikki_reed");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nikki", "Wallin", "faces_girls_nikki_wallin");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Nina", "Dobrev", "faces_girls_nina_dobrev");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Odette", "Annable", "faces_girls_odette_annable");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Olga", "Kurylenko", "faces_girls_olga_kurylenko");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Olivia", "Thirlby", "faces_girls_olivia_thirlby");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Olivia", "Wilde", "faces_girls_olivia_wilde");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Paris", "Hilton", "faces_girls_paris_hilton");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Paz", "Vega", "faces_girls_paz_vega");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Penelope", "Cruz", "faces_girls_penelope_cruz");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Phoebe", "Tonkin", "faces_girls_phoebe_tonkin");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Piper", "Perabo", "faces_girls_piper_perabo");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Poppy", "Corby Tuech", "faces_girls_poppy_corby_tuech");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "Bilson", "faces_girls_rachel_bilson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "Hurd Wood", "faces_girls_rachel_hurd_wood");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "Mcadams", "faces_girls_rachel_mcadams");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachel", "Roberts", "faces_girls_rachel_roberts");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rachelle", "Lefevre", "faces_girls_rachelle_lefevre");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Raquel", "Alessi", "faces_girls_raquel_alessi");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rebecca", "Hall", "faces_girls_rebecca_hall");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rebecca", "Mader", "faces_girls_rebecca_mader");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rebecca", "Romijn", "faces_girls_rebecca_romijn");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Reem", "Kadem", "faces_girls_reem_kadem");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rene", "Russo", "faces_girls_rene_russo");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Reynah", "Oppal", "faces_girls_reynah_oppal");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rhiana", "Griffith", "faces_girls_rhiana_griffith");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rooney", "Mara", "faces_girls_rooney_mara");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rosario", "Dawson", "faces_girls_rosario_dawson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rose", "Leslie", "faces_girls_rose_leslie");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rose", "Mcgowan", "faces_girls_rose_mcgowan");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Roselyn", "Sanchez", "faces_girls_roselyn_sanchez");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Rosie", "Huntington Whiteley", "faces_girls_rosie_huntington_whiteley");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Roxane", "Mesquida", "faces_girls_roxane_mesquida");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Salma", "Hayek", "faces_girls_salma_hayek");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sandy", "Colton", "faces_girls_sandy_colton");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sara", "Canning", "faces_girls_sara_canning");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sarah", "Jeanne Labrosse", "faces_girls_sarah_jeanne_labrosse");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sarah", "Wayne Callies", "faces_girls_sarah_wayne_callies");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sasha", "Barrese", "faces_girls_sasha_barrese");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Scarlett", "Johansson", "faces_girls_scarlett_johansson");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Selita", "Ebanks", "faces_girls_selita_ebanks");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Serinda", "Swan", "faces_girls_serinda_swan");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("", "Shakira", "faces_girls_shakira");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Shay", "Mitchell", "faces_girls_shay_mitchell");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sofia", "Vergara", "faces_girls_sofia_vergara");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sonia", "Vera", "faces_girls_sonia_vera");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Sophie", "Turner", "faces_girls_sophie_turner");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Stana", "Katic", "faces_girls_stana_katic");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Taylor", "Swift", "faces_girls_taylor_swift");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Teresa", "Palmer", "faces_girls_teresa_palmer");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Thandie", "Newton", "faces_girls_thandie_newton");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tika", "Sumpter", "faces_girls_tika_sumpter");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Traci", "Dinwiddie", "faces_girls_traci_dinwiddie");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tracy", "Spiridakos", "faces_girls_tracy_spiridakos");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tricia", "Helfer", "faces_girls_tricia_helfer");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Tuppence", "Middleton", "faces_girls_tuppence_middleton");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Uma", "Thurman", "faces_girls_uma_thurman");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Valerie", "Azlynn", "faces_girls_valerie_azlynn");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Vanessa", "Lengies", "faces_girls_vanessa_lengies");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Victoria", "Gracie", "faces_girls_victoria_gracie");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Violante", "Placido", "faces_girls_violante_placido");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Virginia", "Bowers", "faces_girls_virginia_bowers");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Willa", "Holland", "faces_girls_willa_holland");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Winona", "Ryder", "faces_girls_winona_ryder");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Yanelba", "Ferreira", "faces_girls_yanelba_ferreira");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Yasmin", "Le Bon", "faces_girls_yasmin_le_bon");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Yunjin", "Kim", "faces_girls_yunjin_kim");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zana", "Salobir", "faces_girls_zana_salobir");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zoe", "Saldana", "faces_girls_zoe_saldana");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zoie", "Palmer", "faces_girls_zoie_palmer");
		girlsFaceMap.put(face.getId(), face);
		face = new Face("Zooey", "Deschanel", "faces_girls_zooey_deschanel");
		girlsFaceMap.put(face.getId(), face);

		//boys
		face = new Face("Aaron", "Eckhart", "faces_boys_aaron_eckhart");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Aaron", "Schwartz", "faces_boys_aaron_schwartz");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Adam", "Sandler", "faces_boys_adam_sandler");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Adrien", "Brody", "faces_boys_adrien_brody");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Al", "Pacino", "faces_boys_al_pacino");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Alan", "Rickman", "faces_boys_alan_rickman");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Alec", "Baldwin", "faces_boys_alec_baldwin");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Alex", "Pettyfer", "faces_boys_alex_pettyfer");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Andrew", "Divoff", "faces_boys_andrew_divoff");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Andrew", "Garfield", "faces_boys_andrew_garfield");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Andrew", "Lincoln", "faces_boys_andrew_lincoln");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Anthony", "Hopkins", "faces_boys_anthony_hopkins");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Anthony", "Mackie", "faces_boys_anthony_mackie");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Anton", "Yelchin", "faces_boys_anton_yelchin");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Antonio", "Banderas", "faces_boys_antonio_banderas");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Arnold", "Schwarzenegger", "faces_boys_arnold_schwarzenegger");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Affleck", "faces_boys_ben_affleck");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Foster", "faces_boys_ben_foster");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Kingsley", "faces_boys_ben_kingsley");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ben", "Stiller", "faces_boys_ben_stiller");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Benedict", "Cumberbatch", "faces_boys_benedict_cumberbatch");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bill", "Murray", "faces_boys_bill_murray");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brad", "Pitt", "faces_boys_brad_pitt");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bradley", "Cooper", "faces_boys_bradley_cooper");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brendan", "Gleeson", "faces_boys_brendan_gleeson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brett", "Cullen", "faces_boys_brett_cullen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Brian", "Tee", "faces_boys_brian_tee");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bruce", "Davison", "faces_boys_bruce_davison");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Bruce", "Willis", "faces_boys_bruce_willis");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Cam", "Gigandet", "faces_boys_cam_gigandet");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Casey", "Affleck", "faces_boys_casey_affleck");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chace", "Crawford", "faces_boys_chace_crawford");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Channing", "Tatum", "faces_boys_channing_tatum");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Charlie", "Sheen", "faces_boys_charlie_sheen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Cooper", "faces_boys_chris_cooper");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Evans", "faces_boys_chris_evans");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Hemsworth", "faces_boys_chris_hemsworth");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Lowell", "faces_boys_chris_lowell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Odonnell", "faces_boys_chris_odonnell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Penn", "faces_boys_chris_penn");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Chris", "Pine", "faces_boys_chris_pine");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christian", "Bale", "faces_boys_christian_bale");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christoph", "Waltz", "faces_boys_christoph_waltz");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christopher", "Lambert", "faces_boys_christopher_lambert");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christopher", "Lee", "faces_boys_christopher_lee");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Christopher", "Walken", "faces_boys_christopher_walken");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Cillian", "Murphy", "faces_boys_cillian_murphy");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Clint", "Eastwood", "faces_boys_clint_eastwood");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Clive", "Owen", "faces_boys_clive_owen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colin", "Farrell", "faces_boys_colin_farrell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colin", "Firth", "faces_boys_colin_firth");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colm", "Feore", "faces_boys_colm_feore");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Colton", "Haynes", "faces_boys_colton_haynes");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dan", "Aykroyd", "faces_boys_dan_aykroyd");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dane", "Cook", "faces_boys_dane_cook");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Craig", "faces_boys_daniel_craig");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Dae Kim", "faces_boys_daniel_dae_kim");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Day Lewis", "faces_boys_daniel_day_lewis");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Daniel", "Radcliffe", "faces_boys_daniel_radcliffe");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Danny", "Devito", "faces_boys_danny_devito");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Danny", "Huston", "faces_boys_danny_huston");
		boysFaceMap.put(face.getId(), face);
		face = new Face("David", "Oakes", "faces_boys_david_oakes");
		boysFaceMap.put(face.getId(), face);
		face = new Face("David", "Wenham", "faces_boys_david_wenham");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dennis", "Quaid", "faces_boys_dennis_quaid");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Denzel", "Washington", "faces_boys_denzel_washington");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dominic", "Cooper", "faces_boys_dominic_cooper");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dominic", "Monaghan", "faces_boys_dominic_monaghan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dominic", "Rains", "faces_boys_dominic_rains");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Don", "Cheadle", "faces_boys_don_cheadle");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Donald", "Sutherland", "faces_boys_donald_sutherland");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dustin", "Hoffman", "faces_boys_dustin_hoffman");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dustin", "Milligan", "faces_boys_dustin_milligan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Dylan", "Walsh", "faces_boys_dylan_walsh");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ed", "Harris", "faces_boys_ed_harris");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ed", "Westwick", "faces_boys_ed_westwick");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Eddie", "Murphy", "faces_boys_eddie_murphy");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Edi", "Gathegi", "faces_boys_edi_gathegi");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Edward", "Norton", "faces_boys_edward_norton");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Elijah", "Wood", "faces_boys_elijah_wood");
		boysFaceMap.put(face.getId(), face);
		face = new Face("", "Eminem", "faces_boys_eminem");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Eric", "Bana", "faces_boys_eric_bana");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ethan", "Hawke", "faces_boys_ethan_hawke");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Eugene", "Byrd", "faces_boys_eugene_byrd");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ewan", "Mcgregor", "faces_boys_ewan_mcgregor");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Faran", "Tahir", "faces_boys_faran_tahir");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Forest", "Whitaker", "faces_boys_forest_whitaker");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Frank", "Grillo", "faces_boys_frank_grillo");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Garrett", "Hedlund", "faces_boys_garrett_hedlund");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Gary", "Oldman", "faces_boys_gary_oldman");
		boysFaceMap.put(face.getId(), face);
		face = new Face("George", "Clooney", "faces_boys_george_clooney");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Gerard", "Butler", "faces_boys_gerard_butler");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Giovanni", "Ribisi", "faces_boys_giovanni_ribisi");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Greg", "Kinnear", "faces_boys_greg_kinnear");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Guy", "Pearce", "faces_boys_guy_pearce");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Harrison", "Ford", "faces_boys_harrison_ford");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Harvey", "Keitel", "faces_boys_harvey_keitel");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Henry", "Cavill", "faces_boys_henry_cavill");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Henry", "Ian Cusick", "faces_boys_henry_ian_cusick");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Hugh", "Dancy", "faces_boys_hugh_dancy");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Hugh", "Jackman", "faces_boys_hugh_jackman");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Hugh", "Laurie", "faces_boys_hugh_laurie");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ian", "Holm", "faces_boys_ian_holm");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ian", "Somerhalder", "faces_boys_ian_somerhalder");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Idris", "Elba", "faces_boys_idris_elba");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Isaac", "Hempstead Wright", "faces_boys_isaac_hempstead_wright");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jack", "Black", "faces_boys_jack_black");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jack", "Gleeson", "faces_boys_jack_gleeson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jack", "Nicholson", "faces_boys_jack_nicholson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jackie", "Chan", "faces_boys_jackie_chan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "Cromwell", "faces_boys_james_cromwell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "Franco", "faces_boys_james_franco");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "Mcavoy", "faces_boys_james_mcavoy");
		boysFaceMap.put(face.getId(), face);
		face = new Face("James", "Phelps", "faces_boys_james_phelps");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jamie", "Dornan", "faces_boys_jamie_dornan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jamie", "Foxx", "faces_boys_jamie_foxx");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jared", "Leto", "faces_boys_jared_leto");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Flemyng", "faces_boys_jason_flemyng");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Isaacs", "faces_boys_jason_isaacs");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Segel", "faces_boys_jason_segel");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jason", "Statham", "faces_boys_jason_statham");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jean", "Reno", "faces_boys_jean_reno");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeff", "Bridges", "faces_boys_jeff_bridges");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeff", "Fahey", "faces_boys_jeff_fahey");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeffrey", "Dean Morgan", "faces_boys_jeffrey_dean_morgan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jensen", "Ackles", "faces_boys_jensen_ackles");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeremy", "Irons", "faces_boys_jeremy_irons");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jeremy", "Renner", "faces_boys_jeremy_renner");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jesse", "Eisenberg", "faces_boys_jesse_eisenberg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jesse", "Spencer", "faces_boys_jesse_spencer");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jet", "Li", "faces_boys_jet_li");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jim", "Carrey", "faces_boys_jim_carrey");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jim", "Caviezel", "faces_boys_jim_caviezel");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jj", "Feild", "faces_boys_jj_feild");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jk", "Simmons", "faces_boys_jk_simmons");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Joaquin", "Phoenix", "faces_boys_joaquin_phoenix");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Joe", "Manganiello", "faces_boys_joe_manganiello");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Carroll Lynch", "faces_boys_john_carroll_lynch");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Cusack", "faces_boys_john_cusack");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Malkovich", "faces_boys_john_malkovich");
		boysFaceMap.put(face.getId(), face);
		face = new Face("John", "Travolta", "faces_boys_john_travolta");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Johnny", "Depp", "faces_boys_johnny_depp");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Johnny", "Whitworth", "faces_boys_johnny_whitworth");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jon", "Favreau", "faces_boys_jon_favreau");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jon", "Voight", "faces_boys_jon_voight");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jonah", "Hill", "faces_boys_jonah_hill");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jorge", "Garcia", "faces_boys_jorge_garcia");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Joseph", "Gordon Levitt", "faces_boys_joseph_gordon_levitt");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Brolin", "faces_boys_josh_brolin");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Dallas", "faces_boys_josh_dallas");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Duhamel", "faces_boys_josh_duhamel");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Hartnett", "faces_boys_josh_hartnett");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Henderson", "faces_boys_josh_henderson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Holloway", "faces_boys_josh_holloway");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Josh", "Lucas", "faces_boys_josh_lucas");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Jude", "Law", "faces_boys_jude_law");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Julian", "Mcmahon", "faces_boys_julian_mcmahon");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Justin", "Long", "faces_boys_justin_long");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Justin", "Timberlake", "faces_boys_justin_timberlake");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Karl", "Urban", "faces_boys_karl_urban");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Keanu", "Reeves", "faces_boys_keanu_reeves");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kellan", "Lutz", "faces_boys_kellan_lutz");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ken", "Leung", "faces_boys_ken_leung");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ken", "Watanabe", "faces_boys_ken_watanabe");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kett", "Turton", "faces_boys_kett_turton");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Bacon", "faces_boys_kevin_bacon");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Costner", "faces_boys_kevin_costner");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Durand", "faces_boys_kevin_durand");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Spacey", "faces_boys_kevin_spacey");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kevin", "Zegers", "faces_boys_kevin_zegers");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kiefer", "Sutherland", "faces_boys_kiefer_sutherland");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kit", "Harington", "faces_boys_kit_harington");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kris", "Kristofferson", "faces_boys_kris_kristofferson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kristian", "Nairn", "faces_boys_kristian_nairn");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kurt", "Russell", "faces_boys_kurt_russell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Kyle", "Gallner", "faces_boys_kyle_gallner");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Laurence", "Fishburne", "faces_boys_laurence_fishburne");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Leonardo", "Dicaprio", "faces_boys_leonardo_dicaprio");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Liam", "Cunningham", "faces_boys_liam_cunningham");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Liam", "Hemsworth", "faces_boys_liam_hemsworth");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Liam", "Neeson", "faces_boys_liam_neeson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Linus", "Roache", "faces_boys_linus_roache");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Logan", "Marshall Green", "faces_boys_logan_marshall_green");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Lucas", "Till", "faces_boys_lucas_till");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Luke", "Wilson", "faces_boys_luke_wilson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Macaulay", "Culkin", "faces_boys_macaulay_culkin");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mads", "Mikkelsen", "faces_boys_mads_mikkelsen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mark", "Gantt", "faces_boys_mark_gantt");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mark", "Ruffalo", "faces_boys_mark_ruffalo");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mark", "Wahlberg", "faces_boys_mark_wahlberg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Martin", "Lawrence", "faces_boys_martin_lawrence");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Martin", "Sheen", "faces_boys_martin_sheen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Bomer", "faces_boys_matt_bomer");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Czuchry", "faces_boys_matt_czuchry");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Damon", "faces_boys_matt_damon");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matt", "Lanter", "faces_boys_matt_lanter");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matthew", "Fox", "faces_boys_matthew_fox");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matthew", "Mcconaughey", "faces_boys_matthew_mcconaughey");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Matthew", "Perry", "faces_boys_matthew_perry");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Max", "Irons", "faces_boys_max_irons");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Max", "Thieriot", "faces_boys_max_thieriot");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Max", "Von Sydow", "faces_boys_max_von_sydow");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mel", "Gibson", "faces_boys_mel_gibson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "C Hall", "faces_boys_michael_c_hall");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Caine", "faces_boys_michael_caine");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Douglas", "faces_boys_michael_douglas");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Emerson", "faces_boys_michael_emerson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Fassbender", "faces_boys_michael_fassbender");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Madsen", "faces_boys_michael_madsen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Pitt", "faces_boys_michael_pitt");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Michael", "Sheen", "faces_boys_michael_sheen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Mickey", "Rourke", "faces_boys_mickey_rourke");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Milo", "Ventimiglia", "faces_boys_milo_ventimiglia");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Morgan", "Freeman", "faces_boys_morgan_freeman");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nathan", "Fillion", "faces_boys_nathan_fillion");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Naveen", "Andrews", "faces_boys_naveen_andrews");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Neal", "Mcdonough", "faces_boys_neal_mcdonough");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Neil", "Patrick Harris", "faces_boys_neil_patrick_harris");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Niall", "Matter", "faces_boys_niall_matter");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nicholas", "Hoult", "faces_boys_nicholas_hoult");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nicolas", "Cage", "faces_boys_nicolas_cage");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Nikolaj", "Coster Waldu", "faces_boys_nikolaj_coster_waldu");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Oliver", "Phelps", "faces_boys_oliver_phelps");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Orlando", "Bloom", "faces_boys_orlando_bloom");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Owen", "Wilson", "faces_boys_owen_wilson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Patrick", "Stewart", "faces_boys_patrick_stewart");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Patrick", "Wilson", "faces_boys_patrick_wilson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Bettany", "faces_boys_paul_bettany");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Dano", "faces_boys_paul_dano");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Giamatti", "faces_boys_paul_giamatti");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Rudd", "faces_boys_paul_rudd");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Paul", "Walker", "faces_boys_paul_walker");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Penn", "Badgley", "faces_boys_penn_badgley");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Peter", "Dinklage", "faces_boys_peter_dinklage");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Peter", "Facinelli", "faces_boys_peter_facinelli");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Pierce", "Brosnan", "faces_boys_pierce_brosnan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Quentin", "Tarantino", "faces_boys_quentin_tarantino");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ralph", "Fiennes", "faces_boys_ralph_fiennes");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ray", "Park", "faces_boys_ray_park");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Richard", "Gere", "faces_boys_richard_gere");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Rob", "Lowe", "faces_boys_rob_lowe");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "De Niro", "faces_boys_robert_de_niro");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Downey Jr", "faces_boys_robert_downey_jr");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Duvall", "faces_boys_robert_duvall");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Knepper", "faces_boys_robert_knepper");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Pattinson", "faces_boys_robert_pattinson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robert", "Sean Leonard", "faces_boys_robert_sean_leonard");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Robin", "Williams", "faces_boys_robin_williams");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Rupert", "Grint", "faces_boys_rupert_grint");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Russell", "Crowe", "faces_boys_russell_crowe");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ryan", "Gosling", "faces_boys_ryan_gosling");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Ryan", "Reynolds", "faces_boys_ryan_reynolds");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sam", "Rockwell", "faces_boys_sam_rockwell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Samuel", "L Jackson", "faces_boys_samuel_l_jackson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Scott", "Caan", "faces_boys_scott_caan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Scott", "Speedman", "faces_boys_scott_speedman");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sean", "Bean", "faces_boys_sean_bean");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sean", "Connery", "faces_boys_sean_connery");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sean", "Penn", "faces_boys_sean_penn");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Seth", "Rogen", "faces_boys_seth_rogen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Shawn", "Ashmore", "faces_boys_shawn_ashmore");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Shia", "Labeouf", "faces_boys_shia_labeouf");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Simon", "Baker", "faces_boys_simon_baker");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Simon", "Pegg", "faces_boys_simon_pegg");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Stanley", "Tucci", "faces_boys_stanley_tucci");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Stephen", "Dorff", "faces_boys_stephen_dorff");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Steve", "Buscemi", "faces_boys_steve_buscemi");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Steve", "Carell", "faces_boys_steve_carell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Steve", "Martin", "faces_boys_steve_martin");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Sylvester", "Stallone", "faces_boys_sylvester_stallone");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tadanobu", "Asano", "faces_boys_tadanobu_asano");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Taylor", "Lautner", "faces_boys_taylor_lautner");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Terence", "Stamp", "faces_boys_terence_stamp");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Terrence", "Howard", "faces_boys_terrence_howard");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Terry", "Oquinn", "faces_boys_terry_oquinn");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Thomas", "Jane", "faces_boys_thomas_jane");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tim", "Roth", "faces_boys_tim_roth");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tobey", "Maguire", "faces_boys_tobey_maguire");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Cruise", "faces_boys_tom_cruise");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Felton", "faces_boys_tom_felton");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Hanks", "faces_boys_tom_hanks");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Hardy", "faces_boys_tom_hardy");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Hiddleston", "faces_boys_tom_hiddleston");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Welling", "faces_boys_tom_welling");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tom", "Wlaschiha", "faces_boys_tom_wlaschiha");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tommy", "Lee Jones", "faces_boys_tommy_lee_jones");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Topher", "Grace", "faces_boys_topher_grace");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Tyler", "Mane", "faces_boys_tyler_mane");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Viggo", "Mortensen", "faces_boys_viggo_mortensen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vin", "Diesel", "faces_boys_vin_diesel");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vincent", "Cassel", "faces_boys_vincent_cassel");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vincent", "Regan", "faces_boys_vincent_regan");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Vinnie", "Jones", "faces_boys_vinnie_jones");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Wentworth", "Miller", "faces_boys_wentworth_miller");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Wes", "Bentley", "faces_boys_wes_bentley");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Wesley", "Snipes", "faces_boys_wesley_snipes");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Ferrell", "faces_boys_will_ferrell");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Patton", "faces_boys_will_patton");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Smith", "faces_boys_will_smith");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Will", "Yun Lee", "faces_boys_will_yun_lee");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Willem", "Dafoe", "faces_boys_willem_dafoe");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Fichtner", "faces_boys_william_fichtner");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Forsythe", "faces_boys_william_forsythe");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Hurt", "faces_boys_william_hurt");
		boysFaceMap.put(face.getId(), face);
		face = new Face("William", "Sadler", "faces_boys_william_sadler");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Woody", "Allen", "faces_boys_woody_allen");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Woody", "Harrelson", "faces_boys_woody_harrelson");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Xavier", "Samuel", "faces_boys_xavier_samuel");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Yul", "Vazquez", "faces_boys_yul_vazquez");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Zac", "Efron", "faces_boys_zac_efron");
		boysFaceMap.put(face.getId(), face);
		face = new Face("Zachary", "Quinto", "faces_boys_zachary_quinto");
		boysFaceMap.put(face.getId(), face);

		girlsFaceIdArray = new int[girlsFaceMap.size()];
		int girlsCount = girlsFaceIdArray.length;
		for (int i = 0; i < girlsCount; ++i) {
			girlsFaceIdArray[i] = i + 1;
		}

		boysFaceIdArray = new int[boysFaceMap.size()];
		int boysCount = boysFaceIdArray.length;
		for (int i = 0; i < boysCount; ++i) {
			boysFaceIdArray[i] = i + 1 + girlsCount;
		}
	}

	public static int[] getGirlsFaceIdArray() {
		return girlsFaceIdArray.clone();
	}

	public static Map<Long, Face> getGirlsFaceMap() {
		return Collections.unmodifiableMap(girlsFaceMap);
	}

	public static int[] getBoysFaceIdArray() {
		return boysFaceIdArray.clone();
	}

	public static Map<Long, Face> getBoysFaceMap() {
		return Collections.unmodifiableMap(boysFaceMap);
	}
}
